### ISSUE TITLE
Missing py dep jupyter_packaging

### ISSUE THREAD

**Issue by jarmitage** [cabreraalex/widget-svelte-cookiecutter#9]
Before I could run:
```sh
jupyter labextension develop --overwrite .
```
I had to do:
```sh
pip install jupyter-packaging
```
Otherwise this errors:
https://github.com/cabreraalex/widget-svelte-cookiecutter/blob/feb467b7e4a29e5a5bee6fffef919b9574fc246f/%7B%7Bcookiecutter.github_project_name%7D%7D/setup.py#L14-L20

**Comment by cabreraalex** [comment]
Honestly even then I can't get that command to work ngl. I added it as a dependency for the dev environment for now. If someone knows the "canonical" way to build for Jupyter Lab that would be great
